# Generated by Django 5.2.5 on 2026-02-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='staff_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
