# Generated by Django 6.0.2 on 2026-03-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_subject_teacher_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, help_text='Select specific students taking this subject. If left empty, all students in the matching Batch/Dept/Year will be considered enrolled.', related_name='elective_subjects', to='assessment.student'),
        ),
    ]
