# Generated by Django 6.0.2 on 2026-03-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_subject_assigned_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='assessment.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_no', 'year', 'batch', 'department')},
        ),
    ]
